# deck-kong-chart/values.yaml
deck:
  namespace: deck-am
  image:
    repository: kong/deck
    tag: latest
  konnectAddress: "https://us.api.konghq.com"
  kongKonnect:
    pat: "kpat_nnsZugrwdpa0CZ6CTxTeXZsYme0daFwYbECfxRW51ybwbZ35K"  # Replace with your actual PAT
  sync:
    enabled: true
    schedule: "* * * * *"

controlPlane:
  name: 2406d123-0746-4b82-a9d2-e2c3c6c0d84b
  config: # Here Deck Kong Yaml 
    services:
    - connect_timeout: 60000
      host: petstore.swagger.io
      name: petinventory
      port: 80
      protocol: https
      read_timeout: 60000
      retries: 5
      write_timeout: 60000
      routes:
      - name: inventory
        paths:
        - /v2/store/inventory
        preserve_host: false
        protocols:
        - http
        - https
        regex_priority: 0
        strip_path: true
        https_redirect_status_code: 426
