# deck-kong-chart/values.yaml
deck:
  namespace: deck-am
  image:
    repository: kong/deck
    tag: latest
  konnectAddress: "https://us.api.konghq.com"
  kongKonnect:
    pat: "kpat_nnsZugrwdpa0CZ6CTxTeXZsYme0daFwYbECfxRW51ybwbZ35K"  # Replace with your actual PAT
  sync:
    enabled: true
    schedule: "* * * * *"

controlPlane:
  name: test
  config:
    services:
    - connect_timeout: 60000
      host: example.com
      name: foo
      port: 80
      protocol: http
      read_timeout: 60000
      retries: 5
      write_timeout: 60000
      routes:
      - name: bar
        paths:
        - /bar
        preserve_host: false
        protocols:
        - http
        - https
        regex_priority: 0
        strip_path: true
        https_redirect_status_code: 426