# deck-kong-chart/templates/deck-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: deck
spec:
  type: {{ .Values.deck.service.type }}
  ports:
    - port: {{ .Values.deck.service.port }}
      targetPort: 8080
  selector:
    app: deck
