# deck-kong-chart/templates/deck-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deck
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deck
  template:
    metadata:
      labels:
        app: deck
    spec:
      containers:
      - name: deck
        image: {{ .Values.deck.image.repository }}:{{ .Values.deck.image.tag }}
        ports:
        - containerPort: 8080
        env:
        - name: KONG_ADMIN_URL
          value: {{ .Values.deck.adminurl | quote }}  # Adjust if necessary
        - name: KONG_KONNECT_PAT
          value: {{ .Values.deck.kongKonnect.pat | quote }}  # Using PAT for Kong Konnect