# deck-kong-chart/templates/kong-deck-config.yaml
_format_version: "3.0"
services:
  - name: {{ .Values.kong.api.name }}
    url: {{ .Values.kong.api.url }}
    routes:
      - name: {{ .Values.kong.api.name }}-route
        paths:
          - {{ .Values.kong.api.path }}
